name: Create release on tag push

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Create release
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Zip up the files
        run: zip -r coolant.zip *

      - name: Draft release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          artifacts: "coolant.zip"
          bodyFile: "CHANGELOG.md"
          draft: true
